import { Project } from './types'

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Ondo Finance',
    category: 'bond',
    chain: 'Ethereum',
    tvl: '$632M',
    status: 'active',
    description: '미국 국채 및 회사채를 토큰화하여 온체인에서 수익을 제공하는 플랫폼',
    detail:
      'Ondo Finance는 기관급 금융 상품을 블록체인에 온보딩하는 RWA 프로토콜입니다. OUSG(미국 국채 펀드)와 USDY(달러 수익 토큰) 등의 상품을 통해 투자자에게 안정적인 수익을 제공합니다.',
    website: 'https://ondo.finance',
    launch_date: '2023-01',
    logo_url: '',
    created_at: '2024-01-01',
  },
  {
    id: '2',
    name: 'Maple Finance',
    category: 'bond',
    chain: 'Ethereum',
    tvl: '$184M',
    status: 'active',
    description: '기업 대출을 토큰화하여 온체인 크레딧 마켓을 구축하는 프로토콜',
    detail:
      'Maple Finance는 기관 투자자와 기업 대출자를 연결하는 온체인 대출 플랫폼입니다. 신용 위험을 평가하고 토큰화된 대출 풀을 통해 투명한 대출 시장을 제공합니다.',
    website: 'https://maple.finance',
    launch_date: '2021-05',
    logo_url: '',
    created_at: '2024-01-02',
  },
  {
    id: '3',
    name: 'RealT',
    category: 'real_estate',
    chain: 'Ethereum',
    tvl: '$98M',
    status: 'active',
    description: '미국 부동산을 분할 소유할 수 있는 토큰화 플랫폼',
    detail:
      'RealT는 미국 주거용 부동산을 ERC-20 토큰으로 분할하여 전 세계 투자자가 소액으로 부동산에 투자할 수 있게 합니다. 임대 수익은 매주 스테이블코인으로 분배됩니다.',
    website: 'https://realt.co',
    launch_date: '2019-06',
    logo_url: '',
    created_at: '2024-01-03',
  },
  {
    id: '4',
    name: 'Centrifuge',
    category: 'bond',
    chain: 'Ethereum',
    tvl: '$251M',
    status: 'active',
    description: '실물 자산을 담보로 한 DeFi 대출 인프라 프로토콜',
    detail:
      'Centrifuge는 중소기업의 송장, 부동산 대출, 소비자 금융 등 다양한 실물 자산을 NFT로 토큰화하고 DeFi 유동성 풀에 연결하는 인프라를 제공합니다.',
    website: 'https://centrifuge.io',
    launch_date: '2021-03',
    logo_url: '',
    created_at: '2024-01-04',
  },
  {
    id: '5',
    name: 'Paxos Gold',
    category: 'commodity',
    chain: 'Ethereum',
    tvl: '$510M',
    status: 'active',
    description: '런던 금고에 보관된 실물 금을 1:1로 토큰화한 스테이블 자산',
    detail:
      'Paxos Gold(PAXG)는 런던 금 시장에서 보관되는 실물 금과 1:1로 연동된 ERC-20 토큰입니다. 토큰 1개는 트로이온스 1개의 금을 나타내며, 언제든지 실물 금으로 교환 가능합니다.',
    website: 'https://paxos.com/paxgold',
    launch_date: '2019-09',
    logo_url: '',
    created_at: '2024-01-05',
  },
  {
    id: '6',
    name: 'Backed Finance',
    category: 'bond',
    chain: 'Polygon',
    tvl: '$47M',
    status: 'upcoming',
    description: '유럽 증권거래소 상장 ETF를 온체인으로 가져오는 토큰화 플랫폼',
    detail:
      'Backed Finance는 전통 금융의 ETF와 채권을 블록체인에 토큰화합니다. 규제 준수 구조를 통해 기관 및 개인 투자자에게 접근성 높은 전통 자산 투자 기회를 제공합니다.',
    website: 'https://backed.fi',
    launch_date: '2024-03',
    logo_url: '',
    created_at: '2024-01-06',
  },
  {
    id: '7',
    name: 'Lofty AI',
    category: 'real_estate',
    chain: 'Solana',
    tvl: '$22M',
    status: 'active',
    description: 'Solana 기반 미국 임대 부동산 분할 소유 및 일일 임대 수익 분배 플랫폼',
    detail:
      'Lofty AI는 Solana 블록체인 위에서 미국 주거용 임대 부동산을 $50 단위로 분할 투자할 수 있게 합니다. 임대 수익은 매일 USDC로 지갑에 자동 분배되며, 2차 시장에서 자유롭게 거래 가능합니다.',
    website: 'https://lofty.ai',
    launch_date: '2021-09',
    logo_url: '',
    created_at: '2024-01-07',
  },
  {
    id: '8',
    name: 'Masterworks',
    category: 'art',
    chain: 'Ethereum',
    tvl: '$830M',
    status: 'active',
    description: '블루칩 미술 작품을 주식처럼 분할 소유할 수 있는 미술 투자 플랫폼',
    detail:
      'Masterworks는 Banksy, Basquiat, Picasso 등 블루칩 현대미술 작품을 증권화하여 일반 투자자도 소액으로 미술 시장에 접근할 수 있게 합니다. 작품 판매 시 수익을 지분에 비례해 배분합니다.',
    website: 'https://masterworks.com',
    launch_date: '2019-03',
    logo_url: '',
    created_at: '2024-01-08',
  },
  {
    id: '9',
    name: 'Toucan Protocol',
    category: 'commodity',
    chain: 'Polygon',
    tvl: '$12M',
    status: 'active',
    description: '탄소 크레딧을 블록체인에 토큰화하여 투명한 탄소 시장을 만드는 프로토콜',
    detail:
      'Toucan Protocol은 검증된 탄소 크레딧을 BCT, NCT 등의 ERC-20 토큰으로 변환합니다. 전통 탄소 시장의 불투명성을 해소하고 DeFi와 탄소 시장을 연결하는 인프라를 제공합니다.',
    website: 'https://toucan.earth',
    launch_date: '2021-10',
    logo_url: '',
    created_at: '2024-01-09',
  },
  {
    id: '10',
    name: 'Homebase',
    category: 'real_estate',
    chain: 'Solana',
    tvl: '$5M',
    status: 'upcoming',
    description: '텍사스 상업용 부동산을 Solana 기반으로 분할 소유하는 플랫폼',
    detail:
      'Homebase는 Solana 블록체인 위에서 미국 텍사스 지역 상업용 부동산에 분산 투자할 수 있게 합니다. 높은 처리량과 낮은 수수료의 Solana 특성을 활용해 소액 투자자도 참여 가능합니다.',
    website: 'https://homebasedao.io',
    launch_date: '2024-06',
    logo_url: '',
    created_at: '2024-01-10',
  },
  {
    id: '11',
    name: 'Superstate',
    category: 'bond',
    chain: 'Ethereum',
    tvl: '$143M',
    status: 'active',
    description: '미국 단기 국채 펀드를 온체인 토큰으로 제공하는 자산운용사',
    detail:
      'Superstate는 규제를 준수하는 온체인 펀드를 운영하는 자산운용사입니다. USTB 토큰을 통해 미국 단기 재무부 채권(T-Bill)에 투자하고, 기관 투자자에게 온체인 국채 수익을 제공합니다.',
    website: 'https://superstate.co',
    launch_date: '2023-08',
    logo_url: '',
    created_at: '2024-01-11',
  },
  {
    id: '12',
    name: 'Tether Gold',
    category: 'commodity',
    chain: 'Ethereum',
    tvl: '$720M',
    status: 'active',
    description: '스위스 금고 보관 실물 금을 1:1로 토큰화한 XAUt 스테이블 자산',
    detail:
      'Tether Gold(XAUt)는 스위스 금고에 보관된 실물 금과 연동된 ERC-20 토큰입니다. 토큰 보유자는 언제든지 실물 금 인출을 요청할 수 있으며, 제3자 감사를 통해 준비금을 정기적으로 검증합니다.',
    website: 'https://gold.tether.to',
    launch_date: '2020-01',
    logo_url: '',
    created_at: '2024-01-12',
  },
]
